name: Get Jackets
on: [workflow_dispatch]
jobs:
  get-jackets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: UV
        uses: astral-sh/setup-uv@v6.0.1
      - name: run jacket script
        working-directory: utils
        run: ./download_assets.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
